package business.controller.CORBA;


/**
* ergebnissdaten/Ergebniss/_ergebnissbereitstellungStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ergebnisse.idl
* Montag, 19. November 2012 17:06 Uhr MEZ
*/

public class _ergebnissbereitstellungStub extends org.omg.CORBA.portable.ObjectImpl implements ergebnissbereitstellung
{

  public String getErgebnisse (String sportart, String liga, String datum)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getErgebnisse", true);
                $out.write_string (sportart);
                $out.write_string (liga);
                $out.write_string (datum);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getErgebnisse (sportart, liga, datum        );
            } finally {
                _releaseReply ($in);
            }
  } // getErgebnisse

  public boolean sindVollstaendig (String sportart, String liga, String datum)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sindVollstaendig", true);
                $out.write_string (sportart);
                $out.write_string (liga);
                $out.write_string (datum);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sindVollstaendig (sportart, liga, datum        );
            } finally {
                _releaseReply ($in);
            }
  } // sindVollstaendig

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ergebnissdaten/Ergebniss/ergebnissbereitstellung:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ergebnissbereitstellungStub
