package business.controller.CORBA;


/**
* ergebnissdaten/Ergebniss/ergebnissbereitstellungPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ergebnisse.idl
* Montag, 19. November 2012 17:06 Uhr MEZ
*/

public abstract class ergebnissbereitstellungPOA extends org.omg.PortableServer.Servant
 implements ergebnissbereitstellungOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getErgebnisse", new java.lang.Integer (0));
    _methods.put ("sindVollstaendig", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ergebnissdaten/Ergebniss/ergebnissbereitstellung/getErgebnisse
       {
         String sportart = in.read_string ();
         String liga = in.read_string ();
         String datum = in.read_string ();
         String $result = null;
         $result = this.getErgebnisse (sportart, liga, datum);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ergebnissdaten/Ergebniss/ergebnissbereitstellung/sindVollstaendig
       {
         String sportart = in.read_string ();
         String liga = in.read_string ();
         String datum = in.read_string ();
         boolean $result = false;
         $result = this.sindVollstaendig (sportart, liga, datum);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ergebnissdaten/Ergebniss/ergebnissbereitstellung:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ergebnissbereitstellung _this() 
  {
    return ergebnissbereitstellungHelper.narrow(
    super._this_object());
  }

  public ergebnissbereitstellung _this(org.omg.CORBA.ORB orb) 
  {
    return ergebnissbereitstellungHelper.narrow(
    super._this_object(orb));
  }


} // class ergebnissbereitstellungPOA
