package business.controller.CORBA;

/**
* ergebnissdaten/Ergebniss/ergebnissbereitstellungHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ergebnisse.idl
* Montag, 19. November 2012 17:06 Uhr MEZ
*/

abstract public class ergebnissbereitstellungHelper
{
  private static String  _id = "IDL:ergebnissdaten/Ergebniss/ergebnissbereitstellung:1.0";

  public static void insert (org.omg.CORBA.Any a, ergebnissbereitstellung that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ergebnissbereitstellung extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (business.controller.CORBA.ergebnissbereitstellungHelper.id (), "ergebnissbereitstellung");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ergebnissbereitstellung read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ergebnissbereitstellungStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ergebnissbereitstellung value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ergebnissbereitstellung narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ergebnissbereitstellung)
      return (ergebnissbereitstellung)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ergebnissbereitstellungStub stub = new _ergebnissbereitstellungStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ergebnissbereitstellung unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ergebnissbereitstellung)
      return (ergebnissbereitstellung)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ergebnissbereitstellungStub stub = new _ergebnissbereitstellungStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
