package business.controller.CORBA;


/**
* ergebnissdaten/Ergebniss/ergebnissbereitstellung.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ergebnisse.idl
* Montag, 19. November 2012 17:06 Uhr MEZ
*/

public interface ergebnissbereitstellung extends ergebnissbereitstellungOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ergebnissbereitstellung
