package CorbaTournament.Tournament;


/**
* CorbaTournament/Tournament/TounamentControllOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tournament.idl
* Samstag, 17. November 2012 18:20 Uhr MEZ
*/

public interface TounamentControllOperations 
{
  String loadTournaments ();
  String loadTournament (int id);
} // interface TounamentControllOperations
