package CorbaTournament.Tournament;

/**
* CorbaTournament/Tournament/TounamentControllHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tournament.idl
* Dienstag, 20. November 2012 16:44 Uhr MEZ
*/

public final class TounamentControllHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaTournament.Tournament.TounamentControll value = null;

  public TounamentControllHolder ()
  {
  }

  public TounamentControllHolder (CorbaTournament.Tournament.TounamentControll initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaTournament.Tournament.TounamentControllHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaTournament.Tournament.TounamentControllHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaTournament.Tournament.TounamentControllHelper.type ();
  }

}
