package CorbaTournament.Tournament;


/**
* CorbaTournament/Tournament/TounamentControll.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tournament.idl
* Samstag, 17. November 2012 18:20 Uhr MEZ
*/

public interface TounamentControll extends TounamentControllOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TounamentControll
