package CorbaTournament.Tournament;


/**
* CorbaTournament/Tournament/TounamentControllOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tournament.idl
* Dienstag, 20. November 2012 16:44 Uhr MEZ
*/

public interface TounamentControllOperations 
{
  String loadTournaments ();
  boolean isFinished (int id);
  String loadTournament (int id);
} // interface TounamentControllOperations
