package CorbaTournament.Tournament;


/**
* CorbaTournament/Tournament/TounamentControllPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tournament.idl
* Samstag, 17. November 2012 18:20 Uhr MEZ
*/

public abstract class TounamentControllPOA extends org.omg.PortableServer.Servant
 implements CorbaTournament.Tournament.TounamentControllOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("loadTournaments", new java.lang.Integer (0));
    _methods.put ("loadTournament", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaTournament/Tournament/TounamentControll/loadTournaments
       {
         String $result = null;
         $result = this.loadTournaments ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CorbaTournament/Tournament/TounamentControll/loadTournament
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.loadTournament (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaTournament/Tournament/TounamentControll:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TounamentControll _this() 
  {
    return TounamentControllHelper.narrow(
    super._this_object());
  }

  public TounamentControll _this(org.omg.CORBA.ORB orb) 
  {
    return TounamentControllHelper.narrow(
    super._this_object(orb));
  }


} // class TounamentControllPOA
