//Tournament.idl
module CorbaTournament{
    module Tournament{
        interface TounamentControll{
        string loadTournaments();
        boolean isFinished(in long id);
        string loadTournament(in long id);
        };
    };
};
